dist: bionic
language: ruby
rvm:
  - 2.5.7
cache:
  - bundler
addons:
  postgresql: 10
  apt:
    packages:
      - libarchive-dev
      - postgresql-10-postgis-2.4
services:
  - memcached
  - postgresql
env:
  global:
    - OSM_MEMCACHE_SERVERS="127.0.0.1"
before_script:
  - ./script/setup/provision.sh
script:
  - bundle exec rubocop -f fuubar
  - bundle exec rake eslint
  - bundle exec erblint .
  - bundle exec rake test:db
