dist: bionic
language: ruby
rvm:
  - 2.5.3
cache:
  - bundler
addons:
  apt:
    packages:
      - libarchive-dev
services:
  - memcached
env:
  global:
    - OSM_MEMCACHE_SERVERS="127.0.0.1"
before_script:
  - ./script/setup/provision.sh
script:
  - bundle exec rubocop -f fuubar
  - bundle exec rake eslint
  - bundle exec erblint .
  - bundle exec rake test:db
